= SWAMP SCARF to SARIF

////
swamp-scarf-sarif

    Source code: https://github.com/mirswamp/swamp-scarf-sarif
    Project Information: https://continuousassurance.org

Copyright 2018 Yuan Zhe Bugh, James A. Kupsch

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the Lincense is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and 
limitations under the License.
////

Module Version: 0.8.1

Last updated on 10-15-2018

=== Description
The https://continuousassurance.org[Software Assurance Marketplace (SWAMP)] runs software assurance tools, and converts the results of each tool into a common format called SCARF (SWAMP Common Assessment Result Format). There exists a new format being developed by https://www.oasis-open.org[OASIS] called https://github.com/oasis-tcs/sarif-spec[SARIF]. This repository contains a command line program that takes in a SCARF file as well as other data generated by an assessment in SWAMP and outputs a SARIF file. This converter uses https://github.com/mirswamp/swamp-sarif-io[swamp-sarif-io] to create the output file. See its documentation for the SARIF features supported.

=== Usage
----
Usage: ./swamp-scarf-sarif [options]

options:
    --help                         -h print this message
    --version                      -v print version
    --compact                      -c print compactly (no indents)
    --scarf=<FILE>                 -x path to scarf file
    --summary=<FILE>               -s path to assessment_summary file
    --hashes=<FILE>                -l path to file containing list of hashes
    --build=<DIR>                  -b path to build directory
    --error=<STRING>               -e reasons assessment failed
    --output=<FILE>                -o output file name/path
----

=== Examples
This command generates the most complete sarif file possible by providing all the data used by the converter that is available in a SWAMP output directory:
----
swamp-scarf-sarif --scarf $dirName/parsed_results/parsed_results.xml --summary $dirName/results/assessment_summary.xml --hashes $dirName/hashes.txt --build $dirName/build/ --output output.sarif
----
This command generates a sarif file containing an error message indicating that the assessment failed:
----
swamp-scarf-sarif --error "Assessment failed due to incompatible platform" --output output.sarif
----

=== Requirements
The following Perl libraries should be installed for the program to work correctly:

- Memory::Usage
- XML::Twig
- Getopt::Long
- https://github.com/mirswamp/swamp-scarf-io[ScarfXmlReader]
- https://github.com/mirswamp/swamp-sarif-io[SarifJsonWriter]